In [1]:
#For an example
import numpy as np

In [2]:
my_arr = np.arange(100000)   #Demo for testing timing of numpy array
mylist = list(range(100000))

In [3]:
%timeit my_arr2 = my_arr*2

100 μs ± 12.2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
%timeit mylist2 = [x*2 for x in mylist]

17 ms ± 1.74 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


# ndarray: A Multidimensional array Object

In [5]:
data = np.array([[1.5, -0.1, 3],[0,-3,6.5]])    #d2 dimensional array

In [6]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [7]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
#creating ndarray
data = [[2, 4, 5, 6, 3],[2, 45, 7, 4, 3]]
array1 = np.array(data)
array1

array([[ 2,  4,  5,  6,  3],
       [ 2, 45,  7,  4,  3]])

In [11]:
array1.ndim

2

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.empty((2,3,2), dtype=np.int32)     #changing the dimensions

array([[[          0,  1073217536],
        [-1717986918, -1078355559],
        [          0,  1074266112]],

       [[          0,           0],
        [          0, -1073217536],
        [          0,  1075445760]]], dtype=int32)

In [15]:
np.ones(2)

array([1., 1.])

In [16]:
np.ones_like(4)

array(1)

In [17]:
np.full(2, 3) #creating 2 charachter with filling 3

array([3, 3])

In [18]:
arr1 = np.array([3, 5, 2, 5], dtype=np.float64)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr1.astype(np.int32)

array([3, 5, 2, 5], dtype=int32)

In [21]:
int_array = np.arange(10)
caliber = np.array([3, 5, 6, 7, 2], dtype=np.float64)
int_array.astype(caliber.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Arithmetic with NumPy Arrays

In [22]:
arr = np.array([[1, 3, 4], [4, 6, 2]])

In [23]:
arr*arr

array([[ 1,  9, 16],
       [16, 36,  4]])

In [24]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
1/arr

array([[1.        , 0.33333333, 0.25      ],
       [0.25      , 0.16666667, 0.5       ]])

In [26]:
arr**2

array([[ 1,  9, 16],
       [16, 36,  4]])

In [27]:
arr>arr

array([[False, False, False],
       [False, False, False]])

# Indexing

In [28]:
arr = np.arange(10)

In [29]:
arr[2:9:2]

array([2, 4, 6, 8])

In [30]:
arr[5:9:2]

array([5, 7])

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[4]=2

In [33]:
arr

array([0, 1, 2, 3, 2, 5, 6, 7, 8, 9])

In [34]:
arr[:] = 64

In [35]:
arr

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [36]:
arr2d = np.array([[3,4,5,6],[2,3,4,5]])
arr2d[0,2]

np.int64(5)

In [37]:
arr2d[0][2]

np.int64(5)

In [38]:
arr3d = np.array([[[3,4,5,2],[5,6,7,4]],[[3,4,5,5],[3,3,3,3]]])

In [39]:
arr3d[0,1,2]

np.int64(7)

In [40]:
old = arr3d[0].copy()   #if you assigned the value directly so it take address directly
#then if we change the value of old so arr3d also change

In [41]:
old[1,2]=3


In [42]:
arr3d

array([[[3, 4, 5, 2],
        [5, 6, 7, 4]],

       [[3, 4, 5, 5],
        [3, 3, 3, 3]]])

In [43]:
array2d = np.array([[3, 4, 5, 6],[3, 5, 5,7],[3, 5, 6,7 ]])

In [44]:
array2d

array([[3, 4, 5, 6],
       [3, 5, 5, 7],
       [3, 5, 6, 7]])

In [45]:
array2d[1:3, 1:2]

array([[5],
       [5]])

In [46]:
array2d[1:3,1:4]

array([[5, 5, 7],
       [5, 6, 7]])

# Bollean indexing

In [47]:
array = np.array(['bob', 'alice', 'jaguar', 'bob', 'bob', 'james'])

In [48]:
data = np.array([[3,4],[2,4],[1,3], [7,8], [3,9],[5,6]])

In [49]:
#bollean indexing :- we say that it is the filtering
array == 'bob'

array([ True, False, False,  True,  True, False])

In [50]:
5 in data

True

In [51]:
9 in data

True

In [52]:
data[array=='bob']        #newly thing

array([[3, 4],
       [7, 8],
       [3, 9]])

In [53]:
data[array == 'bob', :1]

array([[3],
       [7],
       [3]])

In [54]:
~(array == 'bob')

array([False,  True,  True, False, False,  True])

# Fancy indexing

In [55]:
arr = np.zeros((8, 4))

In [56]:
arr[1]

array([0., 0., 0., 0.])

In [57]:
for i in range(8):
    arr[i] = i+1

In [58]:
arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.]])

In [59]:
#you can pass row number of element as list
arr[[1, 3, 5, 7]]

array([[2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.],
       [8., 8., 8., 8.]])

In [60]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([2., 6., 8., 3.])

In [61]:
arr[[-3, -5, -7]]                # negative indexing

array([[6., 6., 6., 6.],
       [4., 4., 4., 4.],
       [2., 2., 2., 2.]])

In [62]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
arr = np.array([[2,4],[5,6],[6,7]])

In [64]:
np.dot(arr.T, arr) #Matrix multiplication

array([[ 65,  80],
       [ 80, 101]])

In [65]:
arr.T @ arr          # Another method to matrix multiplication

array([[ 65,  80],
       [ 80, 101]])

# Random generation

In [66]:
samples = np.random.standard_normal(size=(4,4))

In [67]:
samples

array([[-1.05016559,  0.79576875,  0.6245115 , -0.66948703],
       [-0.31336112, -0.73445973,  1.50946376, -0.77716474],
       [-0.79553442,  0.90466747, -0.1720492 , -1.18684391],
       [-0.20746784, -0.86249792,  1.66880549, -1.75546928]])

In [68]:
rnd = np.random.default_rng(seed=12345)

In [69]:
sample2 = rnd.standard_normal(size=(2,2))

In [70]:
sample2

array([[-1.42382504,  1.26372846],
       [-0.87066174, -0.25917323]])

In [71]:
type(rnd)

numpy.random._generator.Generator

In [72]:
sample3 = np.random.chisquare(20,45)

In [73]:
sample3

array([14.60546484, 14.88920973, 12.03992354, 19.40271567, 33.33643129,
       18.3273171 , 18.64097693, 20.12209545, 20.10316145, 31.07830526,
       20.86615864, 22.95623956, 30.5393399 , 11.59857307, 17.5864428 ,
       23.57862381, 23.62073659, 17.08669091, 16.78352749,  8.90318007,
       17.42139914, 19.28455171, 11.89797794, 21.91474602, 15.53395645,
       14.23425239, 25.15687045, 19.04370805, 13.9546747 , 20.91268478,
       19.53414857, 15.16596335, 19.85832533, 20.59533911, 23.56810327,
       18.1650206 , 24.23919684, 13.27493074, 27.26327023, 32.85129058,
       26.51078421, 21.558432  , 18.4792602 , 22.24466114, 21.39363157])

# Universal function 

In [74]:
uniarray = np.arange(10)

In [75]:
np.sqrt(uniarray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
np.exp(uniarray)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

/* maximum and minimum also take two function and return a single array

In [77]:
np.maximum(array1, array1)

array([[ 2,  4,  5,  6,  3],
       [ 2, 45,  7,  4,  3]])

In [78]:
arr = rnd.standard_normal(7)

In [79]:
arr

array([-0.07534331, -0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811,
       -1.95286306,  2.34740965])

In [80]:
arr = arr*5

In [81]:
arr

array([-0.37671654, -3.70442326, -6.83896351,  3.24446401,  1.80529057,
       -9.76431532, 11.73704827])

In [82]:
remainder, whole_part = np.modf(arr)   #It is used to sepreate a point part and the whole part

In [83]:
remainder

array([-0.37671654, -0.70442326, -0.83896351,  0.24446401,  0.80529057,
       -0.76431532,  0.73704827])

In [84]:
whole_part

array([-0., -3., -6.,  3.,  1., -9., 11.])

In [85]:
np.add(arr, 1)

array([ 0.62328346, -2.70442326, -5.83896351,  4.24446401,  2.80529057,
       -8.76431532, 12.73704827])

In [86]:
points = np.arange(-5, 5, 0.01)

In [87]:
xs, ys = np.meshgrid(points, points)   #The numpy.meshgrid function takes two one-dimensional arrays and produces two two-dimensional matrices corresponding to all pairs of (x, y) in the two arrays:

In [88]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [89]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [90]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.2, 2.3, 2.4, 2.5, 2.6])
cond = np.array([True, False, True, True, False])

In [91]:
result = [x if c else y for x, y, c in zip(xarr, yarr, cond)]

In [92]:
result

[np.float64(1.1),
 np.float64(2.3),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.6)]

In [93]:
#Do This work by the single call
np.where(cond, xarr, yarr)

array([1.1, 2.3, 1.3, 1.4, 2.6])

In [94]:
result.sort()

In [95]:
result.sort(axis=0)

TypeError: 'axis' is an invalid keyword argument for sort()

In [ ]:
result

In [ ]:
#Suposse we have a randomize matrix Where negative integer can be replace by the 2 and -2
rand = np.random.standard_normal((4,4))

In [ ]:
np.where(rand > 0, 2, -2)

# Statistical method

In [ ]:
arr = np.random.standard_normal((3,4))

In [ ]:
np.mean(arr)

In [ ]:
arr.mean()

In [ ]:
arr.sum()

In [ ]:
arr.sum(axis=0)

In [ ]:
#axis = 0 means perform operation row wise and 1 mean perform operation column wise

In [ ]:
arr.cumsum()

In [ ]:
arr

# Boolean array statistical operation

In [ ]:
(arr>0).sum()

In [ ]:
#Two method are also useful that 
#1.any :- check that the any value is true in array
#2.all :- check that the all value is true or not
arr1 = np.array([True, False, True, True])
arr1.any()
arr1.all()

In [ ]:
arr1.any()

In [96]:
name = np.array(['Bob', 'Bob', 'Will', 'Will', 'Ram', 'Ram', 'love'])
np.unique(name)   #It is use to sort the unique value

array(['Bob', 'Ram', 'Will', 'love'], dtype='<U4')

In [99]:
#numpy.in1d is used as a membership operator
my_array = np.array([3, 5, 66, 7, 3, 2, 7, 2, 4, 0])
np.in1d(my_array, [3, 5, 2])

/tmp/ipykernel_2270/2931275250.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(my_array, [3, 5, 2])


array([ True,  True, False, False,  True,  True, False,  True, False,
       False])

# File input and output with array

In [101]:
#Two main function for save and load file into disk np.save and np.load
arr = np.array([3,5, 7, 8,3, 6, 4, 23])
np.save("array_file", arr)

In [102]:
arr

array([ 3,  5,  7,  8,  3,  6,  4, 23])

In [103]:
np.load("array_file.npy")

array([ 3,  5,  7,  8,  3,  6,  4, 23])

# Liner Algebra: Multiplication , decomposition , determinantes and other square matrix

In [105]:
from numpy.linalg import inv, qr

In [108]:
x = np.random.standard_normal((4,6))
x

array([[-0.64805493, -0.51422284,  0.27359512, -0.01531336, -0.34586168,
        -0.0519699 ],
       [ 1.46287823, -0.13738068, -0.58931923,  0.14168485, -0.55060335,
         0.10398179],
       [ 0.67191507,  0.66958376,  0.18000738, -0.71373273, -0.5759322 ,
         0.53081991],
       [ 2.21518529,  0.46088114, -1.31248806, -0.15367912,  0.67523494,
        -0.95571564]])

In [109]:
mat = x.T @ x

In [110]:
inv(mat)

array([[-3.09726935e+15,  1.62389524e+15, -6.35448111e+15,
        -6.78070256e+14, -1.78475945e+15,  1.17885592e+15],
       [ 3.65313671e+15,  1.27026205e+15,  9.44944321e+15,
         3.84659648e+15, -6.78393815e+14, -4.99487858e+15],
       [-5.10944075e+15,  4.63339720e+15, -9.28353552e+15,
         7.50797945e+14, -4.65203942e+15, -2.66799736e+14],
       [ 1.26277714e+15,  2.38476006e+15,  4.46014706e+15,
         3.19056607e+15, -1.93455796e+15, -3.92807003e+15],
       [-3.55783978e+15, -9.18092426e+14, -9.00719925e+15,
        -3.44111688e+15,  3.81936988e+14,  4.50359963e+15],
       [-1.11719837e+15, -3.01870723e+15, -4.50359963e+15,
        -3.69202555e+15,  2.50567496e+15,  4.50359963e+15]])

In [111]:
mat @ inv(mat)

array([[ 0.3534495 , -0.64686643,  3.        , -0.93751614,  0.61009355,
        -3.        ],
       [-0.879365  ,  0.75299945, -0.9375    , -0.17916024, -0.10751374,
        -0.75      ],
       [-0.68199086, -0.75399725,  4.        ,  0.64115491,  1.33217545,
         1.        ],
       [ 0.40882754,  0.12813753,  0.625     ,  1.47627048, -0.23279071,
        -0.125     ],
       [-1.04013674,  0.3410871 , -2.        , -0.53964755,  1.01189018,
         0.5       ],
       [-0.699524  , -0.10619239,  1.        ,  0.18166574, -0.76771411,
         1.        ]])

In [1]:
#Walking problem
import random

In [3]:
position = 0 
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)

[0,
 1,
 2,
 3,
 2,
 3,
 2,
 3,
 4,
 5,
 4,
 3,
 4,
 3,
 2,
 1,
 0,
 1,
 2,
 3,
 4,
 5,
 4,
 3,
 4,
 5,
 6,
 7,
 6,
 7,
 6,
 7,
 6,
 7,
 8,
 7,
 8,
 7,
 6,
 5,
 4,
 5,
 4,
 5,
 4,
 5,
 4,
 3,
 2,
 1,
 2,
 3,
 4,
 5,
 4,
 3,
 2,
 1,
 2,
 3,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 3,
 2,
 3,
 2,
 3,
 2,
 1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -3,
 -2,
 -3,
 -4,
 -5,
 -4,
 -3,
 -4,
 -3,
 -4,
 -5,
 -4,
 -3,
 -2,
 -1,
 -2,
 -1,
 -2,
 -3,
 -2,
 -1,
 -2,
 -3,
 -4,
 -5,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 0,
 1,
 2,
 3,
 2,
 1,
 0,
 1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 0,
 1,
 0,
 1,
 2,
 3,
 4,
 3,
 2,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 -1,
 -2,
 -3,
 -4,
 -5,
 -4,
 -5,
 -6,
 -7,
 -8,
 -7,
 -8,
 -7,
 -6,
 -5,
 -6,
 -7,
 -6,
 -7,
 -8,
 -9,
 -10,
 -11,
 -12,
 -11,
 -12,
 -11,
 -10,
 -11,
 -10,
 -9,
 -10,
 -9,
 -10,
 -9,
 -8,
 -7,
 -8,
 -7,
 -8,
 -9,
 -10,
 -11,
 -10,
 -9,
 -8,
 -9,
 -8,
 -9,
 -10,
 -9,
 -10,
 -11,
 -10,
 -9,
 -8,
 -9,
 -8,
 -7,
 -8,
 -9,
 -8,
 -7,
 -8,
 -9,
 -8,
 -7,